"""добавление_моделей_активность_работа

Revision ID: 1712992932
Revises: 1712944072
Create Date: 2024-04-13 10:22:12.111013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1712992932'
down_revision: Union[str, None] = '1712944072'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи, первичный ключ, автоинкремент'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Название активности'),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='Состояние активности, доступна ли она для выбора на портале'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата и время создания активности'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='activity_name_key')
    )
    op.create_index(op.f('ix_Activities_id'), 'Activities', ['id'], unique=True)
    op.create_table('WorksDone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID записи, первичный ключ, автоинкремент'),
    sa.Column('user_email', sa.String(length=100), nullable=False, comment='Корпоративный email Пользователя, зафиксировавшего данную активность'),
    sa.Column('completed_in', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата и время выполнения / фиксации работы на портале'),
    sa.Column('activity_id', sa.Integer(), nullable=False, comment='ID типа совершенной / зафиксированной работы'),
    sa.Column('duration_in_minutes', sa.SmallInteger(), nullable=False, comment='Продолжительность зафиксированной работы в минутах'),
    sa.Column('url', sa.String(length=500), nullable=True, comment='Ссылка на задачу / материал в рамках которого велась работа (опционально, не обязательное поле)'),
    sa.Column('description', sa.String(), nullable=False, comment='Описание проделанной работы'),
    sa.ForeignKeyConstraint(['activity_id'], ['Activities.id'], ),
    sa.ForeignKeyConstraint(['user_email'], ['Users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_WorksDone_id'), 'WorksDone', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_WorksDone_id'), table_name='WorksDone')
    op.drop_table('WorksDone')
    op.drop_index(op.f('ix_Activities_id'), table_name='Activities')
    op.drop_table('Activities')
    # ### end Alembic commands ###
