"""первая_ревизия

Revision ID: 1712944072
Revises: 
Create Date: 2024-04-12 20:47:52.803204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1712944072'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('email', sa.String(length=100), nullable=False, comment='Корпоротивный email адрес пользователя по совместительству логин на портале'),
    sa.Column('fullname', sa.String(length=150), nullable=False, comment='Полные ФИО пользователя'),
    sa.Column('hashed_password', sa.String(length=300), nullable=False, comment='Хэш пароля пользователя'),
    sa.Column('active', sa.Boolean(), server_default=sa.text('1'), nullable=False, comment='Отключен ли пользователь'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Дата и время создания пользователя'),
    sa.PrimaryKeyConstraint('email'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_table('Users')
    # ### end Alembic commands ###
